# tensorflow-probability meta data file
{% set name = "tensorflow-probability" %}
{% set version = "0.12.2" %}
{% set estimator_version = "2.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/probability.git
  git_rev: v{{ version }}
  patches:
    - 0002-revert-README-addition.patch

build:
  number: 1
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
    - bazel {{ bazel }}
  host:
    - python {{ python }}
    - tensorflow-base {{ tensorflow }}
    - tensorflow-estimator {{ estimator_version }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - python {{ python }}
    - decorator
    - six {{ six }}
    - numpy {{ numpy }}
    - gast {{ gast }}
    - cloudpickle {{ cloudpickle }}
    - dm-tree {{ dm_tree }}
    - tensorflow-base {{ tensorflow }}
    - tensorflow-estimator {{ estimator_version }}

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'
  description: |
    TensorFlow Probability is a library for probabilistic reasoning
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
